### ISSUE TITLE
小問題

### ISSUE THREAD

**Issue by KamiyaMinoru** [fishjar/kiss-dictionary#1]
請問怎麼下載? 我只找到個別的檔案 沒有打包好的
又, popup的視窗 內容可能是可以選擇繁體中文的嗎
謝謝

**Comment by fishjar** [comment]
1、请问您是什么浏览器？

- firefox 到这里下载： https://addons.mozilla.org/zh-CN/firefox/addon/kiss-dict/
-  chrome 到这里下载：https://chrome.google.com/webstore/detail/%E7%AE%80%E7%BA%A6%E8%AF%8D%E5%85%B8/gjlpjmdbeghafdacfhdelemndidgbfha?hl=zh-CN&authuser=0
- edge 没有上架，需要下载本仓库后，通过`load unpacked`方式安装

2、此插件非常个性化，且配置选项很少，暂时不支持繁体中文。

**Comment by KamiyaMinoru** [comment]
我透過chrome商店安裝在edge上了！謝謝！
